name: publish on modrinth
on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up node JS
              uses: actions/setup-node@v4
              with:
                  node-version: '20.11.0'
            - name: Install dependencies
              run: npm install
            - name: Build
              env: 
                WHITELIST_LINK: ${{ secrets.WHITELIST_LINK }}
                BANNED_PLAYERS_LINK: ${{ secrets.BANNED_PLAYERS_LINK }}
                MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
              run: node index.js
            - name: install zip
              uses: montudor/action-zip@v1
            - name: run zip
              run: zip -qq -r ../skin-pack.zip *
              working-directory: ./skin-pack/
            - uses: Kir-Antipov/mc-publish@v3.3
              with:
                modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
                modrinth-id: ${{ secrets.MODRINTH_ID }}
                name: Trusted pack
                version: 1.0+1.21
                files: skin-pack.zip
                version-type: release
                loaders: minecraft
                game-versions: |
                    >=1.21 <=1.21.1
                game-version-filter: releases
                dependencies: cit-resewn@1.1.5+1.20.4(required)
            
